### ISSUE TITLE
AttributeError: 'TopTurn' object has no attribute 'estimate_dcr'

### ISSUE THREAD

**Issue by StephaneD38** [dzimmanck/python-planar-magnetics#16]
**Describe the bug**
Example code is not working.

**To Reproduce**

I'm runing the following code:

```
from planar_magnetics.inductors import Cffc
from planar_magnetics.utils import weight_to_thickness

# create an inductor using the CFFC technique
inductor = Cffc(inner_radius=4.9, outer_radius=9, number_turns=5, voltage=500)

# estimate the dc resistance of this inductor
# using the CFFC structure, a 5 turn inductor requires 6 layers
# assume we are using 1.5 oz on top/botton and 2oz on interior layers
thicknesses = [
    weight_to_thickness(1.5),
    weight_to_thickness(2),
    weight_to_thickness(2),
    weight_to_thickness(2),
    weight_to_thickness(2),
    weight_to_thickness(1.5),
]

dcr = inductor.estimate_dcr(thicknesses)
print(f"Estimated DCR of this inductor is {dcr*1e3} mOhms")

```

**Result:**

```
python .\cffc1.py
Traceback (most recent call last):
  File "C:\Python\planar\cffc1.py", line 19, in <module>
    dcr = inductor.estimate_dcr(thicknesses)
  File "C:\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\planar_magnetics\inductors\cffc.py", line 199, in estimate_dcr
    return self.winding.estimate_dcr(thicknesses, rho)
  File "C:\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\planar_magnetics\inductors\cffc.py", line 119, in estimate_dcr
    resistance += turn.estimate_dcr(thickness, rho)
AttributeError: 'TopTurn' object has no attribute 'estimate_dcr'
```

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Python Version 3.10
 - Package planar-magnetics version 0.1.6

**Comment by dzimmanck** [comment]
Fixed with PR #17
